INSERT INTO 'SearchItem'('name') VALUES
('Apples'),
('Avocados'),
('Bananas'),
('Berries'),
('Broccoli'),
('Carrots'),
('Celery'),
('Cucumbers'),
('Garlic'),
('Grapefruit'),
('Grapes'),
('Lemons/Limes'),
('Lettuce'),
('Melons'),
('Mushrooms'),
('Onions'),
('Oranges'),
('Peppers'),
('Potatoes'),
('Squash/Zucchini'),
('Tomatoes'),
('Bacon'),
('Beef / Steak'),
('Chicken'),
('Deli Meat'),
('Fish'),
('Ground Beef'),
('Ham'),
('Hot Dogs'),
('Pork'),
('Sausage'),
('Turkey'),
('Bagels'),
('Bread'),
('Cake'),
('Cookies'),
('Dinner Rolls'),
('Donuts'),
('French Bread'),
('Hamburger Buns'),
('Hot Dog Buns'),
('Muffins'),
('Pastries'),
('Pie'),
('Pita Bread'),
('Tortillas'),
('Biscuits'),
('Butter'),
('Cheese'),
('Cookie Dough'),
('Cream Cheese'),
('Dips'),
('Eggs'),
('Half & Half'),
('Milk'),
('Sour Cream'),
('Whip Cream'),
('Yogurt'),
('Baking Powder'),
('Baking Soda'),
('Bread Crumbs'),
('Brownie Mix'),
('Cake Mix'),
('Canned Milk'),
('Chocolate Chips'),
('Cocoa'),
('Cornmeal'),
('Cornstarch'),
('Flour'),
('Food Coloring'),
('Frosting'),
('Muffin Mix'),
('Oatmeal'),
('Pie Crust'),
('Shortening'),
('Sugar (brown)'),
('Sugar (powder)'),
('Sugar (white)'),
('Vanilla'),
('Yeast'),
('Couscous'),
('Hamburger Helper'),
('Lasagna'),
('Mac & Cheese'),
('Macaroni'),
('Noodle Mixes'),
('Ramen'),
('Rice (brown)'),
('Rice (white)'),
('Rice Mixes'),
('Spaghetti'),
('Water'),
('Juice'),
('Soda'),
('Sports Drinks'),
('Coffee'),
('Tea'),
('Candy');